### ISSUE TITLE
Travis failing with release versions

### ISSUE THREAD

**Issue by tferr** [tferr/ASA#22]
First release after moving to Travis CI. It [failed](https://travis-ci.org/tferr/ASA/builds/236857125):

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.8.2:deploy (default-deploy) on project Sholl_Analysis: Failed to deploy artifacts: Could not transfer artifact ca.mcgill:Sholl_Analysis:jar:sources:3.6.13 from/to imagej.releases (dav:http://maven.imagej.net/content/repositories/releases): Failed to transfer file: http://maven.imagej.net/content/repositories/releases/ca/mcgill/Sholl_Analysis/3.6.13/Sholl_Analysis-3.6.13-sources.jar. Return code is: 400 -> [Help 1]
```

@ctrueden Why is that? Presumably because I haven't set up upload credentials anywhere? 
However I do find the new version on http://maven.imagej.net/content/repositories/releases/ca/mcgill/Sholl_Analysis/3.6.13/. Any thoughts?

**Comment by ctrueden** [comment]
I think what happened is that it tried to upload the `-sources` artifact twice, and the second time failed because the remote artifact already existed. I think I have seen this problem before... I am not sure, but it might depend on the version of Maven core used.
```
Uploading: dav:http://maven.imagej.net/content/repositories/releases/ca/mcgill/Sholl_Analysis/3.6.13/Sholl_Analysis-3.6.13-sources.jar
... (succeeded) ...
Uploaded: dav:http://maven.imagej.net/content/repositories/releases/ca/mcgill/Sholl_Analysis/3.6.13/Sholl_Analysis-3.6.13-sources.jar (176 KB at 298.8 KB/sec)
Uploading: dav:http://maven.imagej.net/content/repositories/releases/ca/mcgill/Sholl_Analysis/3.6.13/Sholl_Analysis-3.6.13-sources.jar
... (second attempt to upload the same artifact for some unknown reason) ...
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.8.2:deploy (default-deploy) on project Sholl_Analysis: Failed to deploy artifacts: Could not transfer artifact ca.mcgill:Sholl_Analysis:jar:sources:3.6.13 from/to imagej.releases (dav:http://maven.imagej.net/content/repositories/releases): Failed to transfer file: http://maven.imagej.net/content/repositories/releases/ca/mcgill/Sholl_Analysis/3.6.13/Sholl_Analysis-3.6.13-sources.jar. Return code is: 400 -> [Help 1]
```
Sorry I don't immediately know the best way for us to fix it. Might be best to transition you over to `release-version.sh` to perform your releases, instead of double-push to master. Right now, @stelfrich and I have been discussing/planning the best way to unify the release process for everyone across the community, but we have no iron clad answer yet.

**Comment by tferr** [comment]
Thanks for looking into it. OK no problem, let me know as soon as you guys have a plan. Meanwhile, OK to upload to the Java-8 update site?, or should I wait?

**Comment by ctrueden** [comment]
Uploading to the Java-8 site is OK for now, sure.
