### ISSUE TITLE
Group Sholl Profiles broken

### ISSUE THREAD

**Issue by sparkerino** [tferr/ASA#23]
Hello,

The Group Sholl Profiles command seems to have stopped working with the latest FIJI release. I was using the command without problem, I updated FIJI (which hadn't been done since early this year), and it immediately stopped working. FIJI says command finished, but nothing happens. 

I went back to the May 29th release of FIJI with Sholl 3.6.13 and Group Sholl Profiles works again. Hooray!

I re-installed a fresh version of the newest FIJI release (1.51p) in case something was wrong with mine specifically,  and Group Sholl didn't work. I also tried going back to Sholl 3.6.12 with 1.51p and it still didn't work. So I'm pretty sure there is some issue between 1.51p and the command itself. 

Sara

**Comment by sparkerino** [comment]
Hmmm. I'm also noticing something else strange with Group Sholl Profiles. The resulting combined data seems to stop short of the actual maximum ending radius within the dataset. So, I have a few neurons that have intersections more than 400um from the centroid according to their individual data, but the combined data, Plot and Merged File xls, might stop at 250um, despite several neurons having maximum radii larger than this.

**Comment by tferr** [comment]
@sparkerino,

Could you please try the following:
1) Shift-click on the `Group Profiles...` command to have it open on the script editor
2) Replace  lines [185-186](https://github.com/tferr/ASA/blob/master/src/main/resources/scripts/Analyze/Sholl/Group_Sholl_Profiles....py#L185-L186), simply with `main()`.

Does it work then?

As per the second problem, I am not sure how to address it, there should be nothing in the script that trims data to a certain distance. Can you please place the problematic files you are trying to merge somewhere where I can access them, so that I can have a look?

**Comment by sparkerino** [comment]
Yes, replacing lines 185-186 did work when I press Run from the script editor, and once I save and restart it is fixed-fixed. Thanks!

Here is a google drive link to a folder with a smaller set of my files, as well as the Group Sholl output files. So even though some of the files still have intersections beyond a 225.75 micron radius, it has stopped merging radii beyond that point. I have four data sets, and one has consistently been correct and three have stopped short. In this particular example and one of the other datasets, I found that the first file in the series (2002_crop 2 in this case) has a largest radius of 225.75, so I thought maybe Group Sholl was like using the first file to define the parameters of the merged data. But the "first file max radius" phenomenon only held for two of my four datasets, one was correct and the other was some other number.

https://drive.google.com/drive/folders/0B_g6ROZOnzzjLXpNd1QtUXN6ZG8?usp=sharing

**Comment by tferr** [comment]
Well, it is not actually a bug per se, just badly explained perhaps. As mentioned in the prompt, properties common to all the profiles ( X-values, column heading, etc.) are retrieved from the first file found. In your case the first file found stops at 225.75um. The script keeps appending y-values after that distance as they are parsed from remaining files, it is just they do not show up in the plot. (If you retrieve the plot table you will see that that after 225.75um X-coordinates are just _NaN_). 

Could you please try the new fix (4280fab47d416) and let me know how it  goes? Just copy and paste the [raw script](https://github.com/tferr/ASA/blob/4280fab47d416aa197fc431cfe8203c0516b1a7f/src/main/resources/scripts/Analyze/Sholl/Group_Sholl_Profiles....py) into the Script Editor, choose "Python" as language, and press run.

I want to reiterate that the script still assumes all profiles share the same _starting radius_ and _step size_ (the fix removes the previous restriction of also sharing a common _end radius_), so you may have funky results if otherwise.

> it is fixed-fixed

Well, only for those monitoring this conversion. Changes still need to be uploaded to the ImageJ updater.

Out of curiosity, presumably you will be comparing the grouped profiles across experimental conditions. How are you going to do that?

**Comment by sparkerino** [comment]
Got it, I think I wasn't sure what measurements were a part of the requirement of same structure. My files have same starting and ending radius (I made it uniformly 0 and 2000um in the macro to avoid cutting any file short when batch processing the Sholl Analysis), radius step size is all set to 0.

Just tested it. Tada! Now all my radii are included in the group! Thanks!

I haven't gotten that far to think about how I will actually compare my experimental conditions, but with this fix I will now be ready to analyze in about 5 minutes, so I'd better start thinking! What I saw in another paper is a t test comparing the intersections at each radius value between the two groups. My PI and I were discussing comparing critical value and critical radius, and now that I'm looking at your paper I see that it can be done! I have also made other morphometric measurements from the data in Neurite Tracer, number of primary branches, their length, axon length. Do you have any other suggestions on this?

Thanks a bunch for all your help!

**Comment by tferr** [comment]
@sparkerino,
Sorry for the late reply.  Please note that a new version of the plugin has been released, which includes this fix. Also I highly encourage you to explore the IJ2 rewrite of the plugin now available at _Analyze>Sholl>Sholl Analysis (Experimental version)_

> What I saw in another paper is a t test comparing the intersections at each radius value between the two groups.

This is problematic, to say the least. Please see e.g.,  [Wilson et al.](https://www.ncbi.nlm.nih.gov/pubmed/28104486). I would like to integrate their recommendations in the program but at the moment my time is quite limited.

**Comment by tferr** [comment]
I am closing this, as the issue seems to be solved
